#!/usr/bin/env python3

'''
Descriptions
    Second draft of program to monitor the binary output from a sensor.

    Turn on/off PDU outlet to activate a pump which will remove water.

    Pumping duration will auto adjust given rate of fill per conditions.

Notes
    Design goal is to read the GPIO output continously to check for the
    water level within a condensation tank (any slow fill catch basin).

Dependencies
    Requires:
        1. CQ Robot Water Sensor
        2. Digital Web Loggers PDU
        3. RV Water Pump (tubing, values, ...)
        4. WiFi (between RPi & PDU)

Improvements
    - ...
'''

# ----------------------------------------------------------------------
# Module(s).
# ----------------------------------------------------------------------
import RPi.GPIO as GPIO
import time

# ----------------------------------------------------------------------
# Import environment and data file(s).
# ----------------------------------------------------------------------
import cqr_env

# Define mode to use GPIO pin via BCM pin numbering.
GPIO.setmode(GPIO.BCM)
GPIO.setup(18,GPIO.IN)

def main():
    # Create always true loop.
    try:
        while True:
            # Read the RAW GPIO value (binary).
            CQR_VALUE = GPIO.input(18)
            #print(f"Raw GPIO value: {CQR_VALUE}")
            
            # Report tank condition.
            if CQR_VALUE == 0:
                print(f"{CQR_VALUE}: H2O level is below sensor")
            elif CQR_VALUE == 1:
                print(f"{CQR_VALUE}: H2O level is at sensor")
            else:
                print(f"{CQR_VALUE}: Something is wrong with sensor")

            # Pause.
            time.sleep(cqr_env.TIME_CHECK)
    except KeyboardInterrupt:
        print("Program stopped by user input...")
    finally:
        # Reset GPIO settings.
        GPIO.cleanup()

if __name__ == "__main__":
    """
        Setup to support both "shebang" and "import" code execution
        either as a script and/or imported into another module.
        Isolate all user defined file updates to this section.
    """
    # Optimize for local runtime environment: See cqr_env.py
    
    # Main function to access GPIO data generated by water sensor.
    main()
